finally, finished dz1
45gk/2022-2-VK-EDU-FS-Frontend-I-Razumov pull request #1
Opened 2022-10-04 07:56 UTC by 45gk

# Домашнее задание №1

Прошу @martinkomitsky или @haseprogram проверить его.

Что было сделано:
* Выполнены задания к файлам convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js
* Был написан тест  convertBytesToHuman.test.js
* Проведено успешное тестирование всех 3 функций

2022-10-04 21:09 UTC, martinkomitsky commented on package.json
> +    "yocto-queue": "^0.1.0"
что за список зависимостей? У нас куда меньше должно быть. Нужно все удалить и оставить те, что были на лекции

2022-10-04 21:09 UTC, martinkomitsky requested changes
См. коммент

2022-10-07 17:26 UTC, 45gk commented
> # Домашнее задание №1
> Прошу @martinkomitsky или @HaseProgram проверить его.
> 
> Что было сделано:
> 
> * Выполнены задания к файлам convertBytesToHuman.js, correctSentence.js, nonUniqueElements.js
> * Был написан тест  convertBytesToHuman.test.js
> * Проведено успешное тестирование всех 3 функций
> * Удалены ненужные зависимости

2022-10-10 19:33 UTC, martinkomitsky requested changes
См. снова коммент

2022-10-10 19:33 UTC, martinkomitsky commented on package.json
> +  },
Теперь в файле совсем отсутствуют зависимости. Почему? Как писал в прошлом замечании, в блоке `dependencies` должны быть указаны те библиотеки, которые добавлялись на первом занятии.

2022-10-20 08:10 UTC, martinkomitsky commented
@45gk будут ли исправления? И где следующие ДЗ?

2022-10-20 09:09 UTC, 45gk commented
> @45gk будут ли исправления? И где следующие ДЗ?

Прошу прощение за задержку, был небольшой завал. PR с 2 дз будет в ближайшее время

2022-10-20 09:12 UTC, martinkomitsky approved these changes
12

2022-10-20 09:12 UTC, merged